version: "3"

tasks:
  lint:
    cmds:
      - ruff check . --fix
      - black . --check
      - mypy src/
    desc: Run linter, formatter and static checks

  test:
    desc: Run pytest
    cmds:
      - poetry run pytest

  cli:
    desc: Run CLI with --hello
    cmds:
      - poetry run python -m openrouter_observer --hello