version: "3"

tasks:
  lint:
    cmds:
      - ruff check . --fix
      - black . --check
      - mypy src/
    desc: Run linter, formatter and static checks

  test:
    desc: Run pytest
    cmds:
      - poetry run pytest
