app:
  name: "OpenRouter Observer"
  version: "0.1.0"
  mode: "dev"
  enable_debug: true
  log_path: "logs/sample.log"
  poll_interval: 1.0
  export_path: "exports/observer_output.jsonl"

observer:
  log_level: "INFO"
  max_requests: 100
  source: "logs/sample.log"
